### ISSUE TITLE
[REQ]Some things

### ISSUE THREAD

**Issue by chycken** [K4ryuu/K4-WorldText-API#2]
hello, can you please solve the 'problem' of changing the basic text written on the wall/floor? The other is that the settings of the given map are also included in the settings of the next map and a couple of players indicated that their fps decreased quite a bit because of the wall texts, and sometimes after a map change player cant join to a team and the server crashes, idk why, cant see errors (without this plugin, no crash and player's fps are normal)

**Comment by K4ryuu** [comment]
Grettings,
I'm 99% sure about that your problem is not from this plugin. The plugin not operates with any expensive code or async task. It only spawn entity on round start and that's it. Nothing continuously running or so which could decrease FPS.
